title: tuz86's CTF Writeups
description: "A Collection of writeups for HTB and VulnHub boxes"
author:
  name: "tuz86"
  email: "alex.tulloch86@gmail.com"
  url: "https://tuz86.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "tuz86"
year : "2021"
